name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd src && cargo build --verbose
    - name: Run tests
      run: cd src && cargo test --verbose
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 14.x
    - name: Run test of ejecting
      run: cd src && make init && make sample
